export const PERMISSIONS = {
  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_MANAGE_STATUS: 'users.manage_status',
  USERS_MANAGE_ROLES: 'users.manage_roles',
  ROLES_READ: 'roles.read',
  ROLES_CREATE: 'roles.create',
  ROLES_UPDATE: 'roles.update',
  ROLES_DELETE: 'roles.delete',
  ROLES_MANAGE_PERMISSIONS: 'roles.manage_permissions',
  CATEGORIES_READ: 'categories.read',
  CATEGORIES_CREATE: 'categories.create',
  CATEGORIES_UPDATE: 'categories.update',
  CATEGORIES_MANAGE_STATUS: 'categories.manage_status',
  UNITS_READ: 'units.read',
  UNITS_CREATE: 'units.create',
  UNITS_UPDATE: 'units.update',
  UNITS_MANAGE_STATUS: 'units.manage_status',
  SUPPLIERS_READ: 'suppliers.read',
  SUPPLIERS_CREATE: 'suppliers.create',
  SUPPLIERS_UPDATE: 'suppliers.update',
  SUPPLIERS_MANAGE_STATUS: 'suppliers.manage_status',
  PRODUCTS_READ: 'products.read',
  PRODUCTS_CREATE: 'products.create',
  PRODUCTS_UPDATE: 'products.update',
  PRODUCTS_MANAGE_STATUS: 'products.manage_status',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_LABELS: Readonly<Record<string, string>> = {
  'users.read': 'Visualizar usuários',
  'users.create': 'Criar usuários',
  'users.update': 'Editar usuários',
  'users.manage_status': 'Gerenciar status de usuários',
  'users.manage_roles': 'Gerenciar papéis de usuários',
  'roles.read': 'Visualizar papéis',
  'roles.create': 'Criar papéis',
  'roles.update': 'Editar papéis',
  'roles.delete': 'Excluir papéis',
  'roles.manage_permissions': 'Gerenciar permissões de papéis',
  'categories.read': 'Visualizar categorias',
  'categories.create': 'Criar categorias',
  'categories.update': 'Editar categorias',
  'categories.manage_status': 'Gerenciar status de categorias',
  'units.read': 'Visualizar unidades',
  'units.create': 'Criar unidades',
  'units.update': 'Editar unidades',
  'units.manage_status': 'Gerenciar status de unidades',
  'suppliers.read': 'Visualizar fornecedores',
  'suppliers.create': 'Criar fornecedores',
  'suppliers.update': 'Editar fornecedores',
  'suppliers.manage_status': 'Gerenciar status de fornecedores',
  'products.read': 'Visualizar produtos',
  'products.create': 'Criar produtos',
  'products.update': 'Editar produtos',
  'products.manage_status': 'Gerenciar status de produtos',
};

export const RESOURCE_LABELS: Readonly<Record<string, string>> = {
  users: 'Usuários',
  roles: 'Papéis',
  categories: 'Categorias',
  units: 'Unidades de medida',
  suppliers: 'Fornecedores',
  products: 'Produtos',
};
