export const PERMISSIONS = {
  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_MANAGE_STATUS: 'users.manage_status',
  USERS_MANAGE_ROLES: 'users.manage_roles',
  ROLES_READ: 'roles.read',
  ROLES_CREATE: 'roles.create',
  ROLES_UPDATE: 'roles.update',
  ROLES_DELETE: 'roles.delete',
  ROLES_MANAGE_PERMISSIONS: 'roles.manage_permissions',
  CATEGORIES_READ: 'categories.read',
  CATEGORIES_CREATE: 'categories.create',
  CATEGORIES_UPDATE: 'categories.update',
  CATEGORIES_MANAGE_STATUS: 'categories.manage_status',
  UNITS_READ: 'units.read',
  UNITS_CREATE: 'units.create',
  UNITS_UPDATE: 'units.update',
  UNITS_MANAGE_STATUS: 'units.manage_status',
  SUPPLIERS_READ: 'suppliers.read',
  SUPPLIERS_CREATE: 'suppliers.create',
  SUPPLIERS_UPDATE: 'suppliers.update',
  SUPPLIERS_MANAGE_STATUS: 'suppliers.manage_status',
  PRODUCTS_READ: 'products.read',
  PRODUCTS_CREATE: 'products.create',
  PRODUCTS_UPDATE: 'products.update',
  PRODUCTS_MANAGE_STATUS: 'products.manage_status',
  CUSTOMERS_READ: 'customers.read',
  CUSTOMERS_CREATE: 'customers.create',
  CUSTOMERS_UPDATE: 'customers.update',
  CUSTOMERS_MANAGE_STATUS: 'customers.manage_status',
  WAREHOUSES_READ: 'warehouses.read',
  WAREHOUSES_CREATE: 'warehouses.create',
  WAREHOUSES_UPDATE: 'warehouses.update',
  WAREHOUSES_MANAGE_STATUS: 'warehouses.manage_status',
  STOCK_LOCATIONS_READ: 'stock_locations.read',
  STOCK_LOCATIONS_CREATE: 'stock_locations.create',
  STOCK_LOCATIONS_UPDATE: 'stock_locations.update',
  STOCK_LOCATIONS_MANAGE_STATUS: 'stock_locations.manage_status',
  INVENTORY_READ: 'inventory.read',
  INVENTORY_ENTRY: 'inventory.entry',
  INVENTORY_EXIT: 'inventory.exit',
  INVENTORY_ADJUST: 'inventory.adjust',
  INVENTORY_TRANSFER: 'inventory.transfer',
  INVENTORY_MOVEMENTS_READ: 'inventory.movements.read',
  INVENTORY_COUNTS_READ: 'inventory_counts.read',
  INVENTORY_COUNTS_CREATE: 'inventory_counts.create',
  INVENTORY_COUNTS_COUNT: 'inventory_counts.count',
  INVENTORY_COUNTS_RECOUNT: 'inventory_counts.recount',
  INVENTORY_COUNTS_APPROVE: 'inventory_counts.approve',
  INVENTORY_COUNTS_CANCEL: 'inventory_counts.cancel',
  PURCHASE_ORDERS_READ: 'purchase_orders.read',
  PURCHASE_ORDERS_CREATE: 'purchase_orders.create',
  PURCHASE_ORDERS_UPDATE: 'purchase_orders.update',
  PURCHASE_ORDERS_SUBMIT: 'purchase_orders.submit',
  PURCHASE_ORDERS_APPROVE: 'purchase_orders.approve',
  PURCHASE_ORDERS_CANCEL: 'purchase_orders.cancel',
  PURCHASE_RECEIPTS_READ: 'purchase_receipts.read',
  PURCHASE_RECEIPTS_CREATE: 'purchase_receipts.create',
  SALES_ORDERS_READ: 'sales_orders.read',
  SALES_ORDERS_CREATE: 'sales_orders.create',
  SALES_ORDERS_UPDATE: 'sales_orders.update',
  SALES_ORDERS_CONFIRM: 'sales_orders.confirm',
  SALES_ORDERS_CANCEL: 'sales_orders.cancel',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_LABELS: Readonly<Record<string, string>> = {
  'users.read': 'Visualizar usuários',
  'users.create': 'Criar usuários',
  'users.update': 'Editar usuários',
  'users.manage_status': 'Gerenciar status de usuários',
  'users.manage_roles': 'Gerenciar papéis de usuários',
  'roles.read': 'Visualizar papéis',
  'roles.create': 'Criar papéis',
  'roles.update': 'Editar papéis',
  'roles.delete': 'Excluir papéis',
  'roles.manage_permissions': 'Gerenciar permissões de papéis',
  'categories.read': 'Visualizar categorias',
  'categories.create': 'Criar categorias',
  'categories.update': 'Editar categorias',
  'categories.manage_status': 'Gerenciar status de categorias',
  'units.read': 'Visualizar unidades',
  'units.create': 'Criar unidades',
  'units.update': 'Editar unidades',
  'units.manage_status': 'Gerenciar status de unidades',
  'suppliers.read': 'Visualizar fornecedores',
  'suppliers.create': 'Criar fornecedores',
  'suppliers.update': 'Editar fornecedores',
  'suppliers.manage_status': 'Gerenciar status de fornecedores',
  'products.read': 'Visualizar produtos',
  'products.create': 'Criar produtos',
  'products.update': 'Editar produtos',
  'products.manage_status': 'Gerenciar status de produtos',
  'customers.read': 'Visualizar clientes',
  'customers.create': 'Criar clientes',
  'customers.update': 'Editar clientes',
  'customers.manage_status': 'Gerenciar status de clientes',
  'warehouses.read': 'Visualizar depósitos',
  'warehouses.create': 'Criar depósitos',
  'warehouses.update': 'Editar depósitos',
  'warehouses.manage_status': 'Gerenciar status de depósitos',
  'stock_locations.read': 'Visualizar endereços de estoque',
  'stock_locations.create': 'Criar endereços de estoque',
  'stock_locations.update': 'Editar endereços de estoque',
  'stock_locations.manage_status': 'Gerenciar status de endereços de estoque',
  'inventory.read': 'Visualizar saldos de estoque',
  'inventory.entry': 'Registrar entradas de estoque',
  'inventory.exit': 'Registrar saídas de estoque',
  'inventory.adjust': 'Ajustar saldos de estoque',
  'inventory.transfer': 'Transferir estoque',
  'inventory.movements.read': 'Visualizar movimentações de estoque',
  'inventory_counts.read': 'Visualizar inventários físicos',
  'inventory_counts.create': 'Criar e iniciar inventários físicos',
  'inventory_counts.count': 'Registrar contagens físicas',
  'inventory_counts.recount': 'Solicitar e registrar recontagens',
  'inventory_counts.approve': 'Aprovar inventários físicos',
  'inventory_counts.cancel': 'Cancelar inventários físicos',
  'purchase_orders.read': 'Visualizar pedidos de compra',
  'purchase_orders.create': 'Criar pedidos de compra',
  'purchase_orders.update': 'Editar pedidos de compra',
  'purchase_orders.submit': 'Enviar pedidos para aprovação',
  'purchase_orders.approve': 'Aprovar pedidos de compra',
  'purchase_orders.cancel': 'Cancelar pedidos de compra',
  'purchase_receipts.read': 'Visualizar recebimentos de compras',
  'purchase_receipts.create': 'Confirmar recebimentos de compras',
  'sales_orders.read': 'Visualizar pedidos de venda',
  'sales_orders.create': 'Criar pedidos de venda',
  'sales_orders.update': 'Editar pedidos de venda',
  'sales_orders.confirm': 'Confirmar pedidos de venda',
  'sales_orders.cancel': 'Cancelar pedidos de venda',
};

export const RESOURCE_LABELS: Readonly<Record<string, string>> = {
  users: 'Usuários',
  roles: 'Papéis',
  categories: 'Categorias',
  units: 'Unidades de medida',
  suppliers: 'Fornecedores',
  products: 'Produtos',
  customers: 'Clientes',
  warehouses: 'Depósitos',
  stock_locations: 'Endereços de estoque',
  inventory: 'Estoque',
  'inventory.movements': 'Movimentações de estoque',
  inventory_counts: 'Inventários físicos',
  purchase_orders: 'Pedidos de compra',
  purchase_receipts: 'Recebimentos de compras',
  sales_orders: 'Pedidos de venda',
};
