import { ConflictException, Injectable, NotFoundException } from '@nestjs/common'; import { Prisma } from '@prisma/client'; import type { AuthenticatedUser } from '../auth/auth.types'; import { PrismaService } from '../prisma/prisma.service'; import { CreateUnitDto, ListUnitsQueryDto, UnitResponseDto, UnitStatusFilter, UpdateUnitDto } from './dto/unit.dto';
@Injectable() export class UnitsService {
  constructor(private readonly prisma: PrismaService) {}
  async findAll(identity: AuthenticatedUser, query: ListUnitsQueryDto) { const where: Prisma.UnitOfMeasureWhereInput = { companyId: identity.companyId, ...(query.status ? { isActive: query.status === UnitStatusFilter.ACTIVE } : {}), ...(query.search ? { OR: [{ name: { contains: query.search, mode: 'insensitive' } }, { symbol: { contains: query.search, mode: 'insensitive' } }, { description: { contains: query.search, mode: 'insensitive' } }] } : {}) }; const [units, total] = await this.prisma.$transaction([this.prisma.unitOfMeasure.findMany({ where, skip: (query.page - 1) * query.limit, take: query.limit, orderBy: { [query.sortBy]: query.sortOrder } }), this.prisma.unitOfMeasure.count({ where })]); return { data: units.map((unit) => this.toResponse(unit)), meta: { page: query.page, limit: query.limit, total, totalPages: Math.ceil(total / query.limit) } }; }
  async create(identity: AuthenticatedUser, dto: CreateUnitDto, requestId: string) { const name = dto.name.trim(); const symbol = this.symbol(dto.symbol); try { const unit = await this.prisma.$transaction(async (tx) => { const created = await tx.unitOfMeasure.create({ data: { companyId: identity.companyId, name, normalizedName: this.normalize(name), symbol, normalizedSymbol: this.normalize(symbol), description: dto.description?.trim() } }); await tx.auditLog.create({ data: { actorId: identity.userId, companyId: identity.companyId, entity: 'UnitOfMeasure', entityId: created.id, action: 'unit.created', after: { name: created.name, symbol: created.symbol }, requestId } }); return created; }); return this.toResponse(unit); } catch (error: unknown) { this.rethrowDuplicate(error); } }
  async findOne(identity: AuthenticatedUser, id: string) { return this.toResponse(await this.getScoped(identity.companyId, id)); }
  async update(identity: AuthenticatedUser, id: string, dto: UpdateUnitDto, requestId: string) { const current = await this.getScoped(identity.companyId, id); try { const unit = await this.prisma.$transaction(async (tx) => { const updated = await tx.unitOfMeasure.update({ where: { id }, data: { ...(dto.name !== undefined ? { name: dto.name.trim(), normalizedName: this.normalize(dto.name) } : {}), ...(dto.symbol !== undefined ? { symbol: this.symbol(dto.symbol), normalizedSymbol: this.normalize(this.symbol(dto.symbol)) } : {}), ...(dto.description !== undefined ? { description: dto.description.trim() || null } : {}) } }); await tx.auditLog.create({ data: { actorId: identity.userId, companyId: identity.companyId, entity: 'UnitOfMeasure', entityId: id, action: 'unit.updated', before: { name: current.name, symbol: current.symbol, description: current.description }, after: { name: updated.name, symbol: updated.symbol, description: updated.description }, requestId } }); return updated; }); return this.toResponse(unit); } catch (error: unknown) { this.rethrowDuplicate(error); } }
  async updateStatus(identity: AuthenticatedUser, id: string, isActive: boolean, requestId: string) { const current = await this.getScoped(identity.companyId, id); const unit = await this.prisma.$transaction(async (tx) => { const updated = await tx.unitOfMeasure.update({ where: { id }, data: { isActive } }); await tx.auditLog.create({ data: { actorId: identity.userId, companyId: identity.companyId, entity: 'UnitOfMeasure', entityId: id, action: isActive ? 'unit.activated' : 'unit.deactivated', before: { isActive: current.isActive }, after: { isActive }, requestId } }); return updated; }); return this.toResponse(unit); }
  private async getScoped(companyId: string, id: string) { const unit = await this.prisma.unitOfMeasure.findFirst({ where: { id, companyId } }); if (!unit) throw new NotFoundException({ code: 'UNIT_NOT_FOUND', message: 'Unidade não encontrada.' }); return unit; }
  private normalize(value: string) { return value.trim().replace(/\s+/g, ' ').toLocaleLowerCase('pt-BR'); } private symbol(value: string) { return value.trim().replace(/\s+/g, ' ').toLocaleUpperCase('pt-BR'); }
  private rethrowDuplicate(error: unknown): never { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') throw new ConflictException({ code: 'UNIT_NAME_OR_SYMBOL_EXISTS', message: 'Nome ou símbolo de unidade já utilizado.' }); throw error; }
  private toResponse(unit: { id: string; name: string; symbol: string; description: string | null; isActive: boolean; createdAt: Date; updatedAt: Date }): UnitResponseDto { return { id: unit.id, name: unit.name, symbol: unit.symbol, description: unit.description, isActive: unit.isActive, createdAt: unit.createdAt.toISOString(), updatedAt: unit.updatedAt.toISOString() }; }
}
