import { Body, Controller, Get, Headers, Param, ParseUUIDPipe, Patch, Post, Query, UseGuards } from '@nestjs/common';
import { ApiBearerAuth, ApiConflictResponse, ApiCreatedResponse, ApiForbiddenResponse, ApiNotFoundResponse, ApiOkResponse, ApiTags, ApiUnauthorizedResponse } from '@nestjs/swagger';
import { randomUUID } from 'node:crypto';
import type { AuthenticatedUser } from '../auth/auth.types'; import { CurrentUser } from '../auth/decorators/current-user.decorator'; import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard'; import { PERMISSIONS } from '../authorization/permissions.constants'; import { PermissionsGuard } from '../authorization/permissions.guard'; import { RequirePermissions } from '../authorization/require-permissions.decorator';
import { CategoriesService } from './categories.service'; import { CategoryResponseDto, CreateCategoryDto, ListCategoriesQueryDto, PaginatedCategoriesDto, UpdateCategoryDto, UpdateCategoryStatusDto } from './dto/category.dto';
@ApiTags('Categories') @ApiBearerAuth() @ApiUnauthorizedResponse({ description: 'Sessão inválida.' }) @ApiForbiddenResponse({ description: 'Permissão insuficiente.' }) @UseGuards(JwtAuthGuard, PermissionsGuard) @Controller('categories')
export class CategoriesController { constructor(private readonly service: CategoriesService) {}
  @Get() @RequirePermissions(PERMISSIONS.CATEGORIES_READ) @ApiOkResponse({ type: PaginatedCategoriesDto }) findAll(@CurrentUser() user: AuthenticatedUser, @Query() query: ListCategoriesQueryDto) { return this.service.findAll(user, query); }
  @Post() @RequirePermissions(PERMISSIONS.CATEGORIES_CREATE) @ApiCreatedResponse({ type: CategoryResponseDto }) @ApiConflictResponse({ description: 'Nome já utilizado.' }) create(@CurrentUser() user: AuthenticatedUser, @Body() dto: CreateCategoryDto, @Headers('x-request-id') requestId?: string) { return this.service.create(user, dto, requestId ?? randomUUID()); }
  @Get(':id') @RequirePermissions(PERMISSIONS.CATEGORIES_READ) @ApiOkResponse({ type: CategoryResponseDto }) @ApiNotFoundResponse({ description: 'Categoria não encontrada.' }) findOne(@CurrentUser() user: AuthenticatedUser, @Param('id', new ParseUUIDPipe({ version: '4' })) id: string) { return this.service.findOne(user, id); }
  @Patch(':id') @RequirePermissions(PERMISSIONS.CATEGORIES_UPDATE) @ApiOkResponse({ type: CategoryResponseDto }) update(@CurrentUser() user: AuthenticatedUser, @Param('id', new ParseUUIDPipe({ version: '4' })) id: string, @Body() dto: UpdateCategoryDto, @Headers('x-request-id') requestId?: string) { return this.service.update(user, id, dto, requestId ?? randomUUID()); }
  @Patch(':id/status') @RequirePermissions(PERMISSIONS.CATEGORIES_MANAGE_STATUS) @ApiOkResponse({ type: CategoryResponseDto }) updateStatus(@CurrentUser() user: AuthenticatedUser, @Param('id', new ParseUUIDPipe({ version: '4' })) id: string, @Body() dto: UpdateCategoryStatusDto, @Headers('x-request-id') requestId?: string) { return this.service.updateStatus(user, id, dto.isActive, requestId ?? randomUUID()); }
}
