import { Transform, Type } from 'class-transformer'; import { IsBoolean, IsEnum, IsInt, IsOptional, IsString, Max, MaxLength, Min, MinLength } from 'class-validator'; import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger'; import { PaginationMetaDto } from '../../common/dto/pagination-meta.dto';
const trim = ({ value }: { value: unknown }) => (typeof value === 'string' ? value.trim() : value);
export class CreateUnitDto { @ApiProperty() @Transform(trim) @IsString() @MinLength(2) @MaxLength(120) name!: string; @ApiProperty() @Transform(trim) @IsString() @MinLength(1) @MaxLength(12) symbol!: string; @ApiPropertyOptional() @Transform(trim) @IsOptional() @IsString() @MaxLength(500) description?: string; }
export class UpdateUnitDto { @ApiPropertyOptional() @Transform(trim) @IsOptional() @IsString() @MinLength(2) @MaxLength(120) name?: string; @ApiPropertyOptional() @Transform(trim) @IsOptional() @IsString() @MinLength(1) @MaxLength(12) symbol?: string; @ApiPropertyOptional() @Transform(trim) @IsOptional() @IsString() @MaxLength(500) description?: string; }
export class UpdateUnitStatusDto { @ApiProperty() @IsBoolean() isActive!: boolean; }
export enum UnitStatusFilter { ACTIVE = 'active', INACTIVE = 'inactive' } export enum UnitSortField { NAME = 'name', SYMBOL = 'symbol', CREATED_AT = 'createdAt' } export enum SortOrder { ASC = 'asc', DESC = 'desc' }
export class ListUnitsQueryDto { @ApiPropertyOptional({ default: 1 }) @Type(() => Number) @IsInt() @Min(1) page = 1; @ApiPropertyOptional({ default: 20, maximum: 100 }) @Type(() => Number) @IsInt() @Min(1) @Max(100) limit = 20; @ApiPropertyOptional() @Transform(trim) @IsOptional() @IsString() @MaxLength(100) search?: string; @ApiPropertyOptional({ enum: UnitStatusFilter }) @IsOptional() @IsEnum(UnitStatusFilter) status?: UnitStatusFilter; @ApiPropertyOptional({ enum: UnitSortField, default: UnitSortField.NAME }) @IsOptional() @IsEnum(UnitSortField) sortBy: UnitSortField = UnitSortField.NAME; @ApiPropertyOptional({ enum: SortOrder, default: SortOrder.ASC }) @IsOptional() @IsEnum(SortOrder) sortOrder: SortOrder = SortOrder.ASC; }
export class UnitResponseDto { @ApiProperty({ format: 'uuid' }) id!: string; @ApiProperty() name!: string; @ApiProperty() symbol!: string; @ApiPropertyOptional() description!: string | null; @ApiProperty() isActive!: boolean; @ApiProperty() createdAt!: string; @ApiProperty() updatedAt!: string; }
export class PaginatedUnitsDto { @ApiProperty({ type: [UnitResponseDto] }) data!: UnitResponseDto[]; @ApiProperty({ type: PaginationMetaDto }) meta!: PaginationMetaDto; }
